version: '3.8'
services:
  soccer-media-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soccer-media-db
    ports:
      - '3309:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local